services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8069:8069"
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    container_name: prefect-server
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    restart: unless-stopped


  random-check:
    container_name: random-check
    build:
      context: ./prefect
      dockerfile: Dockerfile
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PYTHONIOENCODING=utf-8
    restart: unless-stopped


volumes:
  prefect_data:
  uptime-kuma-data: